# Generated by Django 4.2.26 on 2026-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='google_verification_file_content',
            field=models.CharField(blank=True, help_text='Une seule ligne, identique au fichier téléchargé depuis Google.', max_length=500),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='google_verification_filename',
            field=models.CharField(blank=True, help_text='Ex. google2c82be27c4a4a6e2.html (tel que fourni par Google).', max_length=120),
        ),
    ]
