# Generated by Django 4.2.26 on 2026-02-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price_per_day', models.PositiveIntegerField(help_text='Prix par jour en FCFA')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('correct', 'Correct'), ('usage', 'Usagé')], default='bon', max_length=20)),
                ('image', models.ImageField(upload_to='equipment/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('is_available', models.BooleanField(default=True)),
                ('requires_driver', models.BooleanField(default=False, help_text='Engin nécessitant un chauffeur')),
                ('driver_price_per_day', models.PositiveIntegerField(default=0, help_text='Prix chauffeur par jour en FCFA')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.category')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentUnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='equipment.equipment')),
            ],
            options={
                'unique_together': {('equipment', 'date')},
            },
        ),
    ]
