# Generated by Django 4.2.26 on 2026-03-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_company_proof_of_address',
            field=models.FileField(blank=True, help_text='Entreprise : justificatif de domicile du siège', null=True, upload_to='kyc/entreprise/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_id_document',
            field=models.FileField(blank=True, help_text='Particulier : pièce d’identité', null=True, upload_to='kyc/particulier/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_proof_of_address',
            field=models.FileField(blank=True, help_text='Particulier : justificatif de domicile', null=True, upload_to='kyc/particulier/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_rc_document',
            field=models.FileField(blank=True, help_text='Entreprise : extrait RC / registre de commerce', null=True, upload_to='kyc/entreprise/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Non soumis'), ('pending_review', 'En attente de vérification'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_tax_document',
            field=models.FileField(blank=True, help_text='Entreprise : NIF / identifiant fiscal', null=True, upload_to='kyc/entreprise/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20),
        ),
    ]
