# Generated by Django 4.2.26 on 2026-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_kyc_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_id_back_document',
            field=models.FileField(blank=True, help_text='Particulier : CNI (verso)', null=True, upload_to='kyc/particulier/', verbose_name='CNI (verso)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_reject_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_company_proof_of_address',
            field=models.FileField(blank=True, help_text='Entreprise : justificatif de domicile du siège', null=True, upload_to='kyc/entreprise/', verbose_name='Justificatif de domicile (siège)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_id_document',
            field=models.FileField(blank=True, help_text='Particulier : CNI (recto)', null=True, upload_to='kyc/particulier/', verbose_name='Pièce d’identité'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_proof_of_address',
            field=models.FileField(blank=True, help_text='Particulier : justificatif de domicile', null=True, upload_to='kyc/particulier/', verbose_name='Justificatif de domicile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_rc_document',
            field=models.FileField(blank=True, help_text='Entreprise : extrait RC / registre de commerce', null=True, upload_to='kyc/entreprise/', verbose_name='Registre de commerce (RC)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_tax_document',
            field=models.FileField(blank=True, help_text='Entreprise : NIF / identifiant fiscal', null=True, upload_to='kyc/entreprise/', verbose_name='NIF / identifiant fiscal'),
        ),
    ]
