# Generated by Django 4.2.26 on 2026-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_kyc_id_back_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy_kyc_consent_at',
            field=models.DateTimeField(blank=True, help_text='Acceptation du traitement des pièces et données pour la vérification KYC.', null=True, verbose_name='Consentement envoi dossier KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_registration_consent_at',
            field=models.DateTimeField(blank=True, help_text='Acceptation du traitement des données lors de la création du compte.', null=True, verbose_name='Consentement inscription'),
        ),
    ]
